### PR TITLE
[CLOUD-474] propagate the real Failure exception

### PR DESCRIPTION
**Pull request by maschmid**

### CODE REVIEW

**Comment by stianst** [comment]
Existing code is not correct, nor is this change. The code should return a 403 if it's not allowed to invoke, but return a 500 if a error occurs. The exception should just be logged in the service IMO.

**Comment by maschmid** [comment]
I see the meaning of the Failure exception together with the "message" span on the page as a way to show users whatever the response of the jaxrs-service was.    Showing "500" would be wrong, as that would seem as if the jaxrs-service returned "500".

**Comment by stianst** [comment]
Not sure I agree, but it doesn't really matter. We're not trying to create a best practice for invoking services, rather showing auth part of it. The most important bit is that users can debug what's going on and what you've done is an improvement there so I'll merge it.

**Comment by stianst** [comment]
Closed wrong button ;)

**Comment by stianst** [comment]
Clicked even... Not easy to do PR reviews on the phone on the bus ;)

**Pull request merged**
