### PR TITLE
Make HTML5 apps deployable as WAR.  Make examples-realm.json for easy

### PR DESCRIPTION
**Pull request by ssilvert**
setup.

### CODE REVIEW

**Comment by stianst** [comment]
The html5 apps should not deploy as a war! They should not be tied to javaee like this. Please undo this

**Comment by stianst** [comment]
The idea was also not to have a pre-conigured realm. Instead there should be client json files.

**Comment by bdaw** [comment]
Needs to be a war so it can be deployed using STI on OpenShift v3 by simple
reference to the repo from the template.

On Sun, Dec 13, 2015 at 4:55 PM, Stian Thorgersen <notifications@github.com>
wrote:

> The idea was also not to have a pre-conigured realm. Instead there should
> be client json files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keycloak/keycloak-examples/pull/5#issuecomment-164270029>
> .
>



-- 
Bolesław Dawidowicz

**Comment by ssilvert** [comment]
I'll do both for the HTML5 examples.

Stian, I don't understand what you mean about client json files.  You want it to use client registration?  It would be nice to have an example for that.

**Comment by stianst** [comment]
Yes, examples should use client registration instead of full realm imports. The readme should also describe how to create the required client. There are no examples for client registration yet, but there's docs + client json files are just standard client representation files.

**Pull request merged**
